#ifndef __PIEZAS_H__
#define __PIEZAS_H__

enum piezas
{
  PEON_BLANCO, PEON_NEGRO,
  TORRE_BLANCA, TORRE_NEGRA,
  CABALLO_BLANCO, CABALLO_NEGRO,
  ALFIL_BLANCO, ALFIL_NEGRO,
  REINA_BLANCA, REINA_NEGRA,
  REY_BLANCO, REY_NEGRO,
  VACIA
};

#endif/*__PIEZAS_H_*/
